---
# Configuration settings
kind: ConfigMap
apiVersion: v1
metadata:
  name: api
  annotations:
    description: API configuration settings
  labels:
    name: api
    part-of: coevent
    version: 1.0.0
    component: api
    managed-by: kustomize
    created-by: jeremy.foster
type: Opaque
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"

  # Authentication
  Authentication__Issuer: "https://coevent.apps.silver.devops.gov.bc.ca/"
  Authentication__Audience: "https://coevent.apps.silver.devops.gov.bc.ca/"
  Authentication__SaltLength: "50"
  Authentication__AccessTokenExpiresIn: "00:05:00"
  Authentication__RefreshTokenExpiresIn: "01:00:00"
