---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: app
  annotations:
    description: Destination for built images.
  labels:
    name: app
    part-of: coevent
    version: 1.0.0
    component: app
    created-by: jeremy.foster

---
# The build config that will be created will be named for the branch you created it for.
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: app.main
  annotations:
    description: Build image from Dockerfile in git repo.
  labels:
    name: app
    part-of: coevent
    version: 1.0.0
    component: app
    created-by: jeremy.foster
    branch: main
spec:
  completionDeadlineSeconds: 2700
  triggers:
    - type: ImageChange
    - type: ConfigChange
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/fosolsolutions/coevent2.0.git
      ref: main
    contextDir: ./app
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.nginx
  output:
    to:
      kind: ImageStreamTag
      name: app:latest
  resources:
    requests:
      cpu: 250m
      memory: 250Mi
    limits:
      cpu: 1500m
      memory: 2Gi
