---
# Keycloak configuration settings.
kind: ConfigMap
apiVersion: v1
metadata:
  name: app
  namespace: default
  annotations:
    description: Keycloak client JSON configuration
  labels:
    name: app
    part-of: coevent
    version: 1.0.0
    component: app
    managed-by: kustomize
    created-by: jeremy.foster
type: Opaque
data:
  keycloak.json: '{
    "realm": "gcpe",
    "auth-server-url": "https://dev.oidc.gov.bc.ca/auth/",
    "ssl-required": "external",
    "resource": "coevent-app",
    "public-client": true,
    "confidential-port": 0
    }'
