kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database
  annotations:
    description: Storage volume
  labels:
    name: database
    part-of: coevent
    version: 1.0.0
    component: database
    created-by: jeremy.foster
    branch: dev
spec:
  # Storage class name is the type of storage [netapp-file-standard, netapp-file-extended, netapp-file-backup, netapp-block-standard, netapp-block-extended]
  storageClassName: netapp-file-standard
  # Storage access mode [ReadWriteOnce, ReadWriteMany]
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
